### PR TITLE
Upgrade to nginx cookbook v8.x

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Stumbled across this while digging into `ds_api_v2` stuff.

Per https://supermarket.chef.io/cookbooks/nginx#changelog, nothing breaking for us.

Cheap to keep up-to-date with this one, and helps ensure whenever we upgrade to Chef 14, it’s easier, since this cookbook handles some deprecations in v8.1.4.

### CODE REVIEW

**Comment by jareyes** [comment]
What kinds of tests did you do to ensure this doesn't break maps or other projects that rely on this cookbook downstream?

**Comment by jeffbyrnes** [comment]
I attempted to test `ds_devsite` locally, which led me to having to clean up that cookbook’s test setup. I’m gonna do a full audit of all the top-level app cookbooks & ensure they’re all testing well generally, as well as with this update.

That said, it still installs NGINX, and for us, configures it the same way. Upgrading like this is a matter of avoiding/decreasing future pain with Chef itself (b/c Chef 14 is a pretty big upgrade, and Chef 13 is EOL early next year).

**Comment by jeffbyrnes** [comment]
Alright, squared away `ds_devsite` enough to validate this works well. Incoming PR for that to get that cookbook back to a good state itself though.

**Comment by jeffbyrnes** [comment]
Thanks to darkskyapp/ds_devsite-cookbook#14, I was able to locally test that this upgrade has no negative impacts on us.

**Comment by jeffbyrnes** [comment]
Right now, yes, this would auto-release everywhere, unless a major/breaking version of `ds_nginx` is issued (i.e., v3.0.0).

`ds_nginx` is directly consumed by various app cookbooks, so that would require manually updating each app cookbook. Laborious, to be sure.

This upgrade doesn’t change anything we use in the `nginx` cookbook, nor does it change the version of NGINX that’s installed. [Full changeset of the `nginx` cookbook](https://github.com/chef-cookbooks/nginx/compare/v7.0.2...v8.1.6) for perusal.

As a result: there won’t be any changes to our NGINX products.

This is, for us, a no-op, and serves only to position us to better receive Chef 14 when the time comes for us to upgrade to it.

I’ve validated that by converging this cookbook in its current form, then again w/ `nginx` v8.x, and made sure no changes occurred that were untoward.

With that in mind, I am planning on issuing a non-breaking change to this cookbook, meaning yes: it will auto-release everywhere.

If there was something breaking, or even something questionable to my eyes, I’d issue a breaking change release to this cookbook, so we could control the release more tightly.

**Pull request merged**
